Fix memory leaks on attend for infinite teamwork instance
hapijs/teamwork pull request #33
Opened 2022-03-21 12:55 UTC by Nargonath

This should fix the memory leak. We empty the `notes` array once the meeting is done. We just need to shallow clone the array when sending it back through the resolved promise. That way we can read the array in userland while clearing the inner array to prevent infinite ref.

I wanted to add a regression test for this but since the `notes` array is private and as far as I know we cannot do referencing counting _natively_, I didn't find a good way to provide a test for it. Does anyone have an idea? @kanongil maybe you have a thought of how to test it?

2022-03-21 13:37 UTC, kanongil commented
You can add a helper method to the `Team` class:

```js
static _notes(team) {

    return team.#notes;
}
```

and use it to verify the state in various tests:

```js
expect(Teamwork.Team._notes(team)).to.…();
```

2022-03-21 13:41 UTC, kanongil requested changes
This PR does not fix the major issue where items can be added to the notes after the meeting is completed.

FYI, I would set `this.#notes = null` rather than mutate the length. This also makes it simple to test that it is done.

2022-03-21 16:27 UTC, Nargonath commented
> You can add a helper method to the `Team` class:
> 
> ```js
> static _notes(team) {
> 
>     return team.#notes;
> }
> ```
> 
> and use it to verify the state in various tests:
> 
> ```js
> expect(Teamwork.Team._notes(team)).to.…();
> ```

Thank you for the suggestion. Is there a reason you're making `_notes` static and not just an instance method? 🤔 

> FYI, I would set this.#notes = null rather than mutate the length. This also makes it simple to test that it is done.

Good suggestion I'll make the change. Thanks.

> This PR does not fix the major issue where items can be added to the notes after the meeting is completed.

Yes indeed, I focused only on the memory leak my bad. I believe also that this is true only if the team is created in _loose_ mode: `strict: false` (which is the default). I see two solutions here:

1) Switch the default to `strict: true` and let the current code handle it.
2) Remove the `strict` behaviour if we don't think it makes sense anymore and make it `strict` by design.

Both of these options are breaking changes though.

FWIW the only usage of the `strict` option I found within the org is in a `h2o2` test: https://github.com/hapijs/h2o2/blob/3f1cdb6a6f790796f5a4fb9a6cfd663b8b985f01/test/index.js#L1969.

I prefer the first solution. It would be the solution that doesn't impact those relying on the `strict` mode but we'd enforce hapi's "security by design" principle for those using the defaults (which I expect to be most users) potentially uncovering _bugs_ in their application. If someone really wants the _loose_ mode, it'd be using it knowingly.

2022-03-22 09:11 UTC, kanongil commented
> Thank you for the suggestion. Is there a reason you're making `_notes` static and not just an instance method? 🤔

Oh, not really. I guess it avoids people discovering a `_notes()` method on the team object and using it.

> > This PR does not fix the major issue where items can be added to the notes after the meeting is completed.

It was not clear, but this is the primary memory leak, which is unresolved. To fix, you just need to do nothing when `attend()` is called when `#done` and not `#strict`. Otherwise it will crash trying to `push()` to a `null` object. There is no breaking change from this.

2022-03-22 10:19 UTC, Nargonath commented
Thanks for the explanation @kanongil. Indeed it's simpler that way. I misinterpreted the _loose_ mode and thought it was part of the design to don't stop the execution when done, my bad. I'll make the changes.

2022-03-29 01:01 UTC, devinivy approved these changes
👍

2022-04-13 11:01 UTC, merged